stages:
  - build
  - test
  - deploy
  - merge

variables:
  GIT_STRATEGY: fetch 

before_script:
  - apt-get update && apt-get install -y git 
  - git config --global user.email "nikalobjanidze014@gmail.com"
  - git config --global user.name "Nikoloz911"
  - git config --global --add safe.directory '*'

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"

lint-test-job:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."

merge_to_master:
  stage: merge
  script:
    - git checkout master
    - git pull origin master
    - git merge origin/test --no-edit
    - git push https://oauth2:${GITLAB_TOKEN}@gitlab.com/Nikoloz911/Portfolio.git master
  only:
    - test
