stages:
  - merge

variables:
  GIT_STRATEGY: fetch 

before_script:
  - apt-get update && apt-get install -y git 
  - git config --global user.email "nikalobjanidze014@gmail.com"
  - git config --global user.name "Nikoloz911"
  - git config --global --add safe.directory '*'

merge_to_master:
  stage: merge
  script:
    - git checkout master
    - git pull origin master
    - git merge origin/test --no-edit
    - git push https://oauth2:${GITLAB_TOKEN}@gitlab.com/Nikoloz911/Portfolio.git master
  only:
    - test
